services:
  - type: web
    name: tds-student-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && playwright install chromium
    startCommand: python -m student.api
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: STUDENT_SECRET
        sync: false
      - key: STUDENT_EMAIL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openai
      - key: API_HOST
        value: 0.0.0.0
    healthCheckPath: /health
